# Data Extraction
---

## Import Libraries

In [16]:
# import libraries
import pandas as pd 
import kagglehub # import data via Kaggle API
import os

import warnings
warnings.filterwarnings("ignore")

## Download Dataset

In [17]:
# Download data from Kaggle to local machine
path = kagglehub.dataset_download("nih-chest-xrays/data")

print("Path to dataset files:", path)

OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /Users/williamnguyen/Documents/GitHub/Deep-Learning-Medical-Diagnosis-Predictor/venv/lib/python3.11/site-packages/certifi/cacert.pem

## Extract Raw Data

In [ ]:
# extract data entry file
data_entry_df = pd.read_csv(os.path.join(path,'Data_Entry_2017.csv'))
data_entry_df.head()

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,0.143,NaN
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143,NaN
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168,NaN
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,0.143,NaN

In [ ]:
# extract bounding box coordinates 
bbox_list = pd.read_csv(os.path.join(path,'BBox_List_2017.csv'))
bbox_list.head()

,Image Index,Finding Label,Bbox [x,y,w,h],Unnamed: 6,Unnamed: 7,Unnamed: 8
0,00013118_008.png,Atelectasis,225.084746,547.019217,86.779661,79.186441,NaN,NaN,NaN
1,00014716_007.png,Atelectasis,686.101695,131.543498,185.491525,313.491525,NaN,NaN,NaN
2,00029817_009.png,Atelectasis,221.830508,317.053115,155.118644,216.949153,NaN,NaN,NaN
3,00014687_001.png,Atelectasis,726.237288,494.951420,141.016949,55.322034,NaN,NaN,NaN
4,00017877_001.png,Atelectasis,660.067797,569.780787,200.677966,78.101695,NaN,NaN,NaN

In [ ]:
# extract test split list
test_list = pd.read_csv(os.path.join(path, 'test_list.txt'))
test_list.shape

(25595, 1)

In [ ]:
# extract train split list
train_val_list = pd.read_csv(os.path.join(path, 'train_val_list.txt'))
train_val_list.shape

(86523, 1)

## Save to Interim

In [ ]:
# Save extracted data to the interim folder as .pkl file

data_entry_df.to_pickle('../data/interim/data_entry_df.pkl')
bbox_list.to_pickle('../data/interim/bbox_list.pkl')
test_list.to_pickle('../data/interim/test_list.pkl')
train_val_list.to_pickle('../data/interim/train_val_list.pkl')